
export const CREDIT_COSTS = {
  CHAT_MESSAGE: 1,
  CHAT_IMAGE_ATTACHMENT: 10,
  GTM_PLAN: 50,
  DOCUMENT_ANALYSIS: 50,
  VIDEO_ANALYSIS: 200,
  IMAGE_GENERATION: 100,
  IMAGE_EDITING: 40,
  VIDEO_GENERATION: 1500,
  WEBSITE_GENERATION: 50,
  MVP_BUILDER: 50, // Explicit key for MVP Builder feature
  // For dashboard quick starts
  MARKET_VALIDATION: 25,
  READY_SET_LAUNCH: 50,
  AUDIENCE_DISCOVERY: 10,
  PRODUCT_SUITE_STRATEGY: 25,
  CUSTOMER_JOURNEY_MAPPING: 25,
  CONTENT_PILLAR_DEVELOPMENT: 15,
  AI_CONTENT_GENERATION: 5,
  FAITH_LENS_QUERY: 5,
};
